=== Daniel-RodriguezFernandez/LaVuelta2026/xml/etapa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" xmlns:uo="http://www.uniovi.es"
	elementFormDefault="qualified" targetNamespace="http://www.uniovi.es"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element name="longitud">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="tipoLongitudEtapa">
								<xs:attribute name="unidad" type="xs:string" fixed="km"
									use="required" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="fecha" />
				<xs:element ref="tiempo_ganador" />
				<xs:element ref="velocidad_media" />
				<xs:element ref="desnivel" />
				<xs:element ref="lugar_salida" />
				<xs:element ref="lugar_meta" />
				<xs:element ref="tipo" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="podcasts" />
				<xs:element ref="salida" />
				<xs:element ref="meta" />
				<xs:element ref="hitos" />
				<xs:element ref="clasificacion_etapa" />
				<xs:element ref="clasificacion_general" />
				<xs:element ref="clasificacion_equipos" />
			</xs:sequence>
			<xs:attribute name="numero" type="tipoNumeroEtapa" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="nombre" type="tipoTexto" />
	<xs:element name="fecha">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:date">
					<xs:attribute name="formato" type="xs:string" fixed="yyyy-MM-dd" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tiempo_ganador" type="tipoTiempoGanador" />
	<xs:element name="velocidad_media">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoVelocidad">
					<xs:attribute name="unidad" type="xs:string" fixed="km/h" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="desnivel">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoDesnivel">
					<xs:attribute name="unidad" type="xs:string" fixed="m" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="lugar_salida" type="tipoTexto" />
	<xs:element name="lugar_meta" type="tipoTexto" />
	<xs:element name="tipo" type="tipoEtapa" />

	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:anyURI" />
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="tipoFotografia" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="tipoVideo" />
	<xs:element name="podcasts">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="podcast" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="podcast" type="tipoPodcast" />

	<xs:element name="salida">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="coordenadas" type="tipoCoordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="meta">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="coordenadas" type="tipoCoordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="tipoCoordenadas">
		<xs:sequence>
			<xs:element ref="latitud" />
			<xs:element name="longitud">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="tipoLongitudGeografica">
							<xs:attribute name="unidad" type="xs:string" fixed="grados"
								use="required" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element ref="altitud" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLatitud">
					<xs:attribute name="unidad" type="xs:string" fixed="grados" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoAltitud">
					<xs:attribute name="unidad" type="xs:string" fixed="m" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="coordenadas" type="tipoCoordenadas" />
				<xs:element ref="distancia_salida" />
			</xs:sequence>
			<xs:attribute name="nombre" type="tipoTexto" use="optional" />
			<xs:attribute name="tipo" type="tipoHito" use="required" />
			<xs:attribute name="bonificado" type="xs:boolean" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia_salida">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoDistanciaSalida">
					<xs:attribute name="unidad" type="xs:string" fixed="km" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="clasificacion_etapa" type="tipoClasificacion">
		<xs:unique name="posicionUnicaEtapa">
			<xs:selector xpath="uo:clasificado" />
			<xs:field xpath="@posicion" />
		</xs:unique>
	</xs:element>
	<xs:element name="clasificacion_general" type="tipoClasificacion">
		<xs:unique name="posicionUnicaGeneral">
			<xs:selector xpath="uo:clasificado" />
			<xs:field xpath="@posicion" />
		</xs:unique>
	</xs:element>
	<xs:element name="clasificacion_equipos" type="tipoClasificacion">
		<xs:unique name="posicionUnicaEquipos">
			<xs:selector xpath="uo:clasificado" />
			<xs:field xpath="@posicion" />
		</xs:unique>
	</xs:element>
	<xs:complexType name="tipoClasificacion">
		<xs:sequence>
			<xs:element minOccurs="3" maxOccurs="3" ref="clasificado" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="clasificado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element minOccurs="0" maxOccurs="1" ref="diferencia_tiempo" />
			</xs:sequence>
			<xs:attribute name="posicion" type="tipoPosicion" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="diferencia_tiempo" type="tipoDiferenciaTiempo" />

	<xs:simpleType name="tipoTexto">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoNumeroEtapa">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="21" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoKm">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="2" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoLongitudEtapa">
		<xs:restriction base="tipoKm">
			<xs:minExclusive value="0" />
			<xs:maxInclusive value="250" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoDistanciaSalida">
		<xs:restriction base="tipoKm">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="250" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoVelocidad">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0" />
			<xs:maxInclusive value="70" />
			<xs:fractionDigits value="2" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoDesnivel">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="6000" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoMetros">
		<xs:restriction base="xs:integer" />
	</xs:simpleType>
	<xs:simpleType name="tipoAltitud">
		<xs:restriction base="tipoMetros">
			<xs:minInclusive value="-100" />
			<xs:maxInclusive value="3500" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoGrados">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="5" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoLatitud">
		<xs:restriction base="tipoGrados">
			<xs:minInclusive value="-90" />
			<xs:maxInclusive value="90" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoLongitudGeografica">
		<xs:restriction base="tipoGrados">
			<xs:minInclusive value="-180" />
			<xs:maxInclusive value="180" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoDuracion">
		<xs:restriction base="xs:duration">
			<xs:pattern value="PT(\d+H)?(\d+M)?(\d+S)?" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoTiempoGanador">
		<xs:restriction base="tipoDuracion">
			<xs:minInclusive value="PT10M" />
			<xs:maxInclusive value="PT7H" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoDiferenciaTiempo">
		<xs:restriction base="tipoDuracion">
			<xs:minExclusive value="PT0S" />
			<xs:maxInclusive value="PT5H" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoEtapa">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Llana" />
			<xs:enumeration value="Media montaña" />
			<xs:enumeration value="Montaña" />
			<xs:enumeration value="Contrarreloj individual" />
			<xs:enumeration value="Contrarreloj por equipos" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoHito">
		<xs:restriction base="xs:string">
			<xs:enumeration value="punto_anonimo" />
			<xs:enumeration value="puerto_especial" />
			<xs:enumeration value="puerto_1a_categoria" />
			<xs:enumeration value="puerto_2a_categoria" />
			<xs:enumeration value="puerto_3a_categoria" />
			<xs:enumeration value="sprint_intermedio" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoFotografia">
		<xs:restriction base="xs:string">
			<xs:pattern value=".+\.(jpg|jpeg|png)" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoVideo">
		<xs:restriction base="xs:string">
			<xs:pattern value=".+\.(mp4|webm)" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoPodcast">
		<xs:restriction base="xs:string">
			<xs:pattern value=".+\.mp3" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoPosicion">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="3" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Daniel-RodriguezFernandez/LaVuelta2026/xml/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<etapa xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es etapa.xsd"
    numero="13">
    <nombre>Almuñécar a Loja</nombre>
    <longitud unidad="km">192.8</longitud>
    <fecha formato="yyyy-MM-dd">2026-09-04</fecha>
    <tiempo_ganador>PT4H34M</tiempo_ganador>
    <velocidad_media unidad="km/h">42.22</velocidad_media>
    <desnivel unidad="m">3404</desnivel>
    <lugar_salida>Almuñécar</lugar_salida>
    <lugar_meta>Loja</lugar_meta>
    <tipo>Media montaña</tipo>
    <referencias>
        <referencia>https://www.lavuelta.es/es/etapa-13</referencia>
        <referencia>
            https://www.lavuelta.es/es/noticias/2026/etapa-13/la-gloria-para-van-aert-llega-desde-la-fuga/64045</referencia>
        <referencia>https://www.lavuelta.es/es/clasificaciones/etapa-13</referencia>
        <referencia>https://www.almunecar.es</referencia>
        <referencia>https://www.aytoloja.org</referencia>
    </referencias>
    <fotografias>
        <fotografia>xmlfotografia1.jpg</fotografia>
    </fotografias>
    <videos>
        <video>xmlvideo1.mp4</video>
    </videos>
    <podcasts>
        <podcast>xmlpodcast1.mp3</podcast>
    </podcasts>
    <salida>
        <coordenadas>
            <latitud unidad="grados">36.74584</latitud>
            <longitud unidad="grados">-3.60947</longitud>
            <altitud unidad="m">86</altitud>
        </coordenadas>
    </salida>
    <meta>
        <coordenadas>
            <latitud unidad="grados">37.16335</latitud>
            <longitud unidad="grados">-4.14153</longitud>
            <altitud unidad="m">498</altitud>
        </coordenadas>
    </meta>
    <hitos>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.74475</latitud>
                <longitud unidad="grados">-3.56318</longitud>
                <altitud unidad="m">20</altitud>
            </coordenadas>
            <distancia_salida unidad="km">4.49</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.78927</latitud>
                <longitud unidad="grados">-3.53779</longitud>
                <altitud unidad="m">72</altitud>
            </coordenadas>
            <distancia_salida unidad="km">10.54</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.81285</latitud>
                <longitud unidad="grados">-3.54181</longitud>
                <altitud unidad="m">104</altitud>
            </coordenadas>
            <distancia_salida unidad="km">13.76</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.84094</latitud>
                <longitud unidad="grados">-3.58199</longitud>
                <altitud unidad="m">327</altitud>
            </coordenadas>
            <distancia_salida unidad="km">20.76</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.83974</latitud>
                <longitud unidad="grados">-3.56430</longitud>
                <altitud unidad="m">470</altitud>
            </coordenadas>
            <distancia_salida unidad="km">22.56</distancia_salida>
        </hito>
        <hito nombre="Alto de la Venta de la Cebada" tipo="puerto_1a_categoria">
            <coordenadas>
                <latitud unidad="grados">36.87248</latitud>
                <longitud unidad="grados">-3.53848</longitud>
                <altitud unidad="m">822</altitud>
            </coordenadas>
            <distancia_salida unidad="km">31.20</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.90862</latitud>
                <longitud unidad="grados">-3.55219</longitud>
                <altitud unidad="m">711</altitud>
            </coordenadas>
            <distancia_salida unidad="km">35.46</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.93014</latitud>
                <longitud unidad="grados">-3.58348</longitud>
                <altitud unidad="m">536</altitud>
            </coordenadas>
            <distancia_salida unidad="km">40.26</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.92958</latitud>
                <longitud unidad="grados">-3.61632</longitud>
                <altitud unidad="m">743</altitud>
            </coordenadas>
            <distancia_salida unidad="km">43.75</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.95661</latitud>
                <longitud unidad="grados">-3.60145</longitud>
                <altitud unidad="m">865</altitud>
            </coordenadas>
            <distancia_salida unidad="km">49.14</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.98562</latitud>
                <longitud unidad="grados">-3.61073</longitud>
                <altitud unidad="m">739</altitud>
            </coordenadas>
            <distancia_salida unidad="km">53.79</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.99053</latitud>
                <longitud unidad="grados">-3.59423</longitud>
                <altitud unidad="m">748</altitud>
            </coordenadas>
            <distancia_salida unidad="km">55.52</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.00918</latitud>
                <longitud unidad="grados">-3.62672</longitud>
                <altitud unidad="m">734</altitud>
            </coordenadas>
            <distancia_salida unidad="km">59.35</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.04933</latitud>
                <longitud unidad="grados">-3.64808</longitud>
                <altitud unidad="m">847</altitud>
            </coordenadas>
            <distancia_salida unidad="km">65.15</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.99040</latitud>
                <longitud unidad="grados">-3.72447</longitud>
                <altitud unidad="m">1142</altitud>
            </coordenadas>
            <distancia_salida unidad="km">75.56</distancia_salida>
        </hito>
        <hito nombre="Alto del Legionario" tipo="puerto_3a_categoria">
            <coordenadas>
                <latitud unidad="grados">36.93527</latitud>
                <longitud unidad="grados">-3.72558</longitud>
                <altitud unidad="m">1350</altitud>
            </coordenadas>
            <distancia_salida unidad="km">83.40</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.95579</latitud>
                <longitud unidad="grados">-3.78451</longitud>
                <altitud unidad="m">1034</altitud>
            </coordenadas>
            <distancia_salida unidad="km">89.51</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.95712</latitud>
                <longitud unidad="grados">-3.85438</longitud>
                <altitud unidad="m">853</altitud>
            </coordenadas>
            <distancia_salida unidad="km">96.48</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.98889</latitud>
                <longitud unidad="grados">-3.87142</longitud>
                <altitud unidad="m">863</altitud>
            </coordenadas>
            <distancia_salida unidad="km">101.60</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.03078</latitud>
                <longitud unidad="grados">-3.94195</longitud>
                <altitud unidad="m">1036</altitud>
            </coordenadas>
            <distancia_salida unidad="km">110.98</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.02244</latitud>
                <longitud unidad="grados">-3.97084</longitud>
                <altitud unidad="m">885</altitud>
            </coordenadas>
            <distancia_salida unidad="km">114.38</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.04155</latitud>
                <longitud unidad="grados">-3.96540</longitud>
                <altitud unidad="m">831</altitud>
            </coordenadas>
            <distancia_salida unidad="km">116.70</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.06835</latitud>
                <longitud unidad="grados">-3.98928</longitud>
                <altitud unidad="m">740</altitud>
            </coordenadas>
            <distancia_salida unidad="km">120.49</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.13059</latitud>
                <longitud unidad="grados">-3.98569</longitud>
                <altitud unidad="m">705</altitud>
            </coordenadas>
