=== Daniel-RodriguezFernandez/LaVuelta2026/xml/etapa.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT etapa (nombre,
                 longitud,
                 fecha,
                 tiempo_ganador,
                 velocidad_media,
                 desnivel,
                 lugar_salida,
                 lugar_meta,
                 tipo,
                 referencias,
                 fotografias,
                 videos,
                 podcasts,
                 salida,
                 meta,
                 hitos,
                 clasificacion_etapa,
                 clasificacion_general,
                 clasificacion_equipos)>
<!ATTLIST etapa numero CDATA #REQUIRED>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidad CDATA #REQUIRED>

<!ELEMENT fecha (#PCDATA)>
<!ATTLIST fecha formato CDATA #REQUIRED>

<!ELEMENT tiempo_ganador (#PCDATA)>
<!ATTLIST tiempo_ganador formato CDATA #REQUIRED>

<!ELEMENT velocidad_media (#PCDATA)>
<!ATTLIST velocidad_media unidad CDATA #REQUIRED>

<!ELEMENT desnivel (#PCDATA)>
<!ATTLIST desnivel unidad CDATA #REQUIRED>

<!ELEMENT lugar_salida (#PCDATA)>
<!ELEMENT lugar_meta (#PCDATA)>

<!ELEMENT tipo (#PCDATA)>

<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT fotografias (fotografia+)>
<!ELEMENT fotografia (#PCDATA)>

<!ELEMENT videos (video+)>
<!ELEMENT video (#PCDATA)>

<!ELEMENT podcasts (podcast+)>
<!ELEMENT podcast (#PCDATA)>

<!ELEMENT salida (coordenadas)>
<!ELEMENT meta (coordenadas)>

<!ELEMENT coordenadas (latitud, longitud, altitud)>

<!ELEMENT latitud (#PCDATA)>
<!ATTLIST latitud unidad CDATA #REQUIRED>

<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud unidad CDATA #REQUIRED>

<!ELEMENT hitos (hito+)>

<!ELEMENT hito (coordenadas, distancia_salida)>
<!ATTLIST hito
          nombre     CDATA          #IMPLIED
          tipo       CDATA          #REQUIRED
          bonificado (true | false) #IMPLIED>

<!ELEMENT distancia_salida (#PCDATA)>
<!ATTLIST distancia_salida unidad CDATA #REQUIRED>

<!ELEMENT clasificacion_etapa (clasificado, clasificado, clasificado)>

<!ELEMENT clasificacion_general (clasificado, clasificado, clasificado)>

<!ELEMENT clasificacion_equipos (clasificado, clasificado, clasificado)>

<!ELEMENT clasificado (nombre, diferencia_tiempo?)>
<!ATTLIST clasificado posicion CDATA #REQUIRED>

<!ELEMENT diferencia_tiempo (#PCDATA)>
<!ATTLIST diferencia_tiempo formato CDATA #REQUIRED>

=== Daniel-RodriguezFernandez/LaVuelta2026/xml/etapa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etapa SYSTEM "etapa.dtd">
<etapa numero="13">
    <nombre>Almuñécar a Loja</nombre>
    <longitud unidad="km">192.8</longitud>
    <fecha formato="yyyy-MM-dd">2026-09-04</fecha>
    <tiempo_ganador formato="hh:mm:ss">04:34:00</tiempo_ganador>
    <velocidad_media unidad="km/h">42.22</velocidad_media>
    <desnivel unidad="m">3404</desnivel>
    <lugar_salida>Almuñécar</lugar_salida>
    <lugar_meta>Loja</lugar_meta>
    <tipo>Media montaña</tipo>
    <referencias>
        <referencia>https://www.lavuelta.es/es/etapa-13</referencia>
        <referencia>
            https://www.lavuelta.es/es/noticias/2026/etapa-13/la-gloria-para-van-aert-llega-desde-la-fuga/64045</referencia>
        <referencia>https://www.lavuelta.es/es/clasificaciones/etapa-13</referencia>
        <referencia>https://www.almunecar.es</referencia>
        <referencia>https://www.aytoloja.org</referencia>
    </referencias>
    <fotografias>
        <fotografia>xmlfotografia1.jpg</fotografia>
    </fotografias>
    <videos>
        <video>xmlvideo1.mp4</video>
    </videos>
    <podcasts>
        <podcast>xmlpodcast1.mp3</podcast>
    </podcasts>
    <salida>
        <coordenadas>
            <latitud unidad="grados">36.74584</latitud>
            <longitud unidad="grados">-3.60947</longitud>
            <altitud unidad="m">86</altitud>
        </coordenadas>
    </salida>
    <meta>
        <coordenadas>
            <latitud unidad="grados">37.16335</latitud>
            <longitud unidad="grados">-4.14153</longitud>
            <altitud unidad="m">498</altitud>
        </coordenadas>
    </meta>
    <hitos>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.74475</latitud>
                <longitud unidad="grados">-3.56318</longitud>
                <altitud unidad="m">20</altitud>
            </coordenadas>
            <distancia_salida unidad="km">4.49</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.78927</latitud>
                <longitud unidad="grados">-3.53779</longitud>
                <altitud unidad="m">72</altitud>
            </coordenadas>
            <distancia_salida unidad="km">10.54</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.81285</latitud>
                <longitud unidad="grados">-3.54181</longitud>
                <altitud unidad="m">104</altitud>
            </coordenadas>
            <distancia_salida unidad="km">13.76</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.84094</latitud>
                <longitud unidad="grados">-3.58199</longitud>
                <altitud unidad="m">327</altitud>
            </coordenadas>
            <distancia_salida unidad="km">20.76</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.83974</latitud>
                <longitud unidad="grados">-3.56430</longitud>
                <altitud unidad="m">470</altitud>
            </coordenadas>
            <distancia_salida unidad="km">22.56</distancia_salida>
        </hito>
        <hito nombre="Alto de la Venta de la Cebada" tipo="puerto_1a_categoria">
            <coordenadas>
                <latitud unidad="grados">36.87248</latitud>
                <longitud unidad="grados">-3.53848</longitud>
                <altitud unidad="m">822</altitud>
            </coordenadas>
            <distancia_salida unidad="km">31.20</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.90862</latitud>
                <longitud unidad="grados">-3.55219</longitud>
                <altitud unidad="m">711</altitud>
            </coordenadas>
            <distancia_salida unidad="km">35.46</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.93014</latitud>
                <longitud unidad="grados">-3.58348</longitud>
                <altitud unidad="m">536</altitud>
            </coordenadas>
            <distancia_salida unidad="km">40.26</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.92958</latitud>
                <longitud unidad="grados">-3.61632</longitud>
                <altitud unidad="m">743</altitud>
            </coordenadas>
            <distancia_salida unidad="km">43.75</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.95661</latitud>
                <longitud unidad="grados">-3.60145</longitud>
                <altitud unidad="m">865</altitud>
            </coordenadas>
            <distancia_salida unidad="km">49.14</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.98562</latitud>
                <longitud unidad="grados">-3.61073</longitud>
                <altitud unidad="m">739</altitud>
            </coordenadas>
            <distancia_salida unidad="km">53.79</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.99053</latitud>
                <longitud unidad="grados">-3.59423</longitud>
                <altitud unidad="m">748</altitud>
            </coordenadas>
            <distancia_salida unidad="km">55.52</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.00918</latitud>
                <longitud unidad="grados">-3.62672</longitud>
                <altitud unidad="m">734</altitud>
            </coordenadas>
            <distancia_salida unidad="km">59.35</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.04933</latitud>
                <longitud unidad="grados">-3.64808</longitud>
                <altitud unidad="m">847</altitud>
            </coordenadas>
            <distancia_salida unidad="km">65.15</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.99040</latitud>
                <longitud unidad="grados">-3.72447</longitud>
                <altitud unidad="m">1142</altitud>
            </coordenadas>
            <distancia_salida unidad="km">75.56</distancia_salida>
        </hito>
        <hito nombre="Alto del Legionario" tipo="puerto_3a_categoria">
            <coordenadas>
                <latitud unidad="grados">36.93527</latitud>
                <longitud unidad="grados">-3.72558</longitud>
                <altitud unidad="m">1350</altitud>
            </coordenadas>
            <distancia_salida unidad="km">83.40</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.95579</latitud>
                <longitud unidad="grados">-3.78451</longitud>
                <altitud unidad="m">1034</altitud>
            </coordenadas>
            <distancia_salida unidad="km">89.51</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.95712</latitud>
                <longitud unidad="grados">-3.85438</longitud>
                <altitud unidad="m">853</altitud>
            </coordenadas>
            <distancia_salida unidad="km">96.48</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">36.98889</latitud>
                <longitud unidad="grados">-3.87142</longitud>
                <altitud unidad="m">863</altitud>
            </coordenadas>
            <distancia_salida unidad="km">101.60</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.03078</latitud>
                <longitud unidad="grados">-3.94195</longitud>
                <altitud unidad="m">1036</altitud>
            </coordenadas>
            <distancia_salida unidad="km">110.98</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.02244</latitud>
                <longitud unidad="grados">-3.97084</longitud>
                <altitud unidad="m">885</altitud>
            </coordenadas>
            <distancia_salida unidad="km">114.38</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.04155</latitud>
                <longitud unidad="grados">-3.96540</longitud>
                <altitud unidad="m">831</altitud>
            </coordenadas>
            <distancia_salida unidad="km">116.70</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.06835</latitud>
                <longitud unidad="grados">-3.98928</longitud>
                <altitud unidad="m">740</altitud>
            </coordenadas>
            <distancia_salida unidad="km">120.49</distancia_salida>
        </hito>
        <hito tipo="punto_anonimo">
            <coordenadas>
                <latitud unidad="grados">37.13059</latitud>
                <longitud unidad="grados">-3.98569</longitud>
                <altitud unidad="m">705</altitud>
            </coordenadas>
            <distancia_salida unidad="km">127.59</distancia_salida>
        </hito>
